import type { Equipment } from '../types';

export const equipment: Equipment[] = [
  {
    id: 1,
    name: 'JCB Excavator - XL450',
    assetId: 'EQ-001',
    status: 'in-use',
    location: 'Site A - Block 3',
    checkedOutBy: 'Rajesh Kumar',
    checkedOutDate: '2026-04-20',
    nextMaintenance: '2026-05-01',
  },
  {
    id: 2,
    name: 'Concrete Mixer - CM250',
    assetId: 'EQ-002',
    status: 'available',
    location: 'Warehouse',
    checkedOutBy: null,
    checkedOutDate: null,
    nextMaintenance: '2026-04-28',
  },
  {
    id: 3,
    name: 'Tower Crane - TC500',
    assetId: 'EQ-003',
    status: 'in-use',
    location: 'Site A - Block 1',
    checkedOutBy: 'Amit Sharma',
    checkedOutDate: '2026-04-15',
    nextMaintenance: '2026-05-15',
  },
  {
    id: 4,
    name: 'Welding Machine - WM100',
    assetId: 'EQ-004',
    status: 'maintenance',
    location: 'Service Center',
    checkedOutBy: null,
    checkedOutDate: null,
    nextMaintenance: '2026-04-26',
  },
  {
    id: 5,
    name: 'Scaffolding Set - SS200',
    assetId: 'EQ-005',
    status: 'available',
    location: 'Warehouse',
    checkedOutBy: null,
    checkedOutDate: null,
    nextMaintenance: '2026-06-01',
  },
];
