import type { MaterialShop } from '../types';

export const materialShops: MaterialShop[] = [
  {
    id: 1,
    name: 'Sharma Building Materials',
    address: '123 MG Road, Sector 12',
    pincode: '400001',
    distance: 1.2,
    rating: 4.5,
    phone: '+91 98765 43210',
    openTime: '8:00 AM - 8:00 PM',
    inventory: [
      { id: 1, name: 'Cement (50kg)', brand: 'UltraTech', stock: 450, unit: 'bags', price: 380 },
      { id: 2, name: 'Steel TMT Bars (12mm)', brand: 'TATA', stock: 85, unit: 'tons', price: 52000 },
      { id: 3, name: 'Bricks (Red Clay)', brand: 'Local', stock: 15000, unit: 'pcs', price: 8 },
      { id: 4, name: 'Sand (M-Sand)', brand: 'Premium', stock: 42, unit: 'tons', price: 1200 },
      { id: 5, name: 'Aggregates (20mm)', brand: 'Standard', stock: 78, unit: 'tons', price: 1500 },
    ],
  },
  {
    id: 2,
    name: 'Kumar Construction Depot',
    address: '45 Industrial Area, Phase 2',
    pincode: '400002',
    distance: 2.8,
    rating: 4.2,
    phone: '+91 98765 43211',
    openTime: '7:30 AM - 7:30 PM',
    inventory: [
      { id: 1, name: 'Cement (50kg)', brand: 'ACC', stock: 320, unit: 'bags', price: 375 },
      { id: 2, name: 'Steel TMT Bars (16mm)', brand: 'JSW', stock: 62, unit: 'tons', price: 54000 },
      { id: 3, name: 'Tiles (Ceramic 2x2)', brand: 'Kajaria', stock: 850, unit: 'sqft', price: 45 },
      { id: 4, name: 'Paint (Exterior)', brand: 'Asian Paints', stock: 125, unit: 'ltrs', price: 450 },
      { id: 5, name: 'Electrical Wiring', brand: 'Polycab', stock: 320, unit: 'mtrs', price: 25 },
      { id: 6, name: 'PVC Pipes', brand: 'Supreme', stock: 280, unit: 'pcs', price: 180 },
    ],
  },
  {
    id: 3,
    name: 'Metro Building Suppliers',
    address: '78 Station Road, Near Metro',
    pincode: '400001',
    distance: 0.8,
    rating: 4.7,
    phone: '+91 98765 43212',
    openTime: '8:00 AM - 9:00 PM',
    inventory: [
      { id: 1, name: 'Cement (50kg)', brand: 'Ambuja', stock: 580, unit: 'bags', price: 385 },
      { id: 2, name: 'Steel TMT Bars (10mm)', brand: 'SAIL', stock: 95, unit: 'tons', price: 50000 },
      { id: 3, name: 'Marble Flooring', brand: 'Italian', stock: 420, unit: 'sqft', price: 120 },
      { id: 4, name: 'Plywood (18mm)', brand: 'Century', stock: 85, unit: 'sheets', price: 1850 },
      { id: 5, name: 'Glass (5mm)', brand: 'Saint Gobain', stock: 140, unit: 'sqft', price: 95 },
    ],
  },
  {
    id: 4,
    name: 'Patel Hardware & Cement Store',
    address: '90 Old Highway, Market Area',
    pincode: '400003',
    distance: 3.5,
    rating: 4.0,
    phone: '+91 98765 43213',
    openTime: '7:00 AM - 8:00 PM',
    inventory: [
      { id: 1, name: 'Cement (50kg)', brand: 'Shree', stock: 280, unit: 'bags', price: 370 },
      { id: 2, name: 'Steel TMT Bars (8mm)', brand: 'Jindal', stock: 48, unit: 'tons', price: 49000 },
      { id: 3, name: 'Bricks (Fly Ash)', brand: 'Eco', stock: 12000, unit: 'pcs', price: 6.5 },
      { id: 4, name: 'Gravel', brand: 'Standard', stock: 55, unit: 'tons', price: 1100 },
      { id: 5, name: 'White Cement', brand: 'Birla', stock: 180, unit: 'bags', price: 580 },
      { id: 6, name: 'Door Frames', brand: 'Teak Wood', stock: 35, unit: 'pcs', price: 4500 },
      { id: 7, name: 'Window Frames', brand: 'Aluminum', stock: 68, unit: 'pcs', price: 2800 },
    ],
  },
];
