import type { Tender } from '../types';

export const tenders: Tender[] = [
  {
    id: 1,
    title: 'Metro Line Extension - Civil Works Package',
    tenderNumber: 'TND-2026-001',
    location: 'Mumbai, Maharashtra',
    issueDate: '2026-03-15',
    closingDate: '2026-05-10',
    status: 'open',
    estimatedValue: 45000000,
    highestBid: 42500000,
    totalBids: 12,
    description: 'Complete civil construction work for 5km metro line extension including tunneling, station structures, and ancillary works.',
    attachments: [
      { name: 'Technical Specifications.pdf', size: '4.2 MB' },
      { name: 'BOQ.xlsx', size: '1.8 MB' },
      { name: 'Site Drawings.dwg', size: '12.5 MB' },
    ],
    category: 'Infrastructure',
  },
  {
    id: 2,
    title: 'Residential Complex - Structural Steel Supply',
    tenderNumber: 'TND-2026-002',
    location: 'Bangalore, Karnataka',
    issueDate: '2026-04-01',
    closingDate: '2026-04-28',
    status: 'upcoming',
    estimatedValue: 28000000,
    highestBid: null,
    totalBids: 0,
    description: 'Supply and installation of structural steel for 20-storey residential towers. TMT bars, H-beams, and connection hardware included.',
    attachments: [
      { name: 'Material Specifications.pdf', size: '2.1 MB' },
      { name: 'Quantity Schedule.xlsx', size: '890 KB' },
    ],
    category: 'Materials',
  },
  {
    id: 3,
    title: 'Highway Expansion - Asphalt & Paving',
    tenderNumber: 'TND-2026-003',
    location: 'Delhi NCR',
    issueDate: '2026-02-10',
    closingDate: '2026-04-20',
    status: 'closed',
    estimatedValue: 62000000,
    highestBid: 58750000,
    totalBids: 18,
    description: '35km highway expansion with premium asphalt paving, road markings, and drainage systems. Includes quality testing and maintenance period.',
    attachments: [
      { name: 'Project Scope.pdf', size: '6.8 MB' },
      { name: 'Technical Requirements.pdf', size: '3.2 MB' },
      { name: 'Site Survey.pdf', size: '9.1 MB' },
    ],
    category: 'Infrastructure',
  },
  {
    id: 4,
    title: 'Commercial Building - MEP Systems',
    tenderNumber: 'TND-2026-004',
    location: 'Pune, Maharashtra',
    issueDate: '2026-04-10',
    closingDate: '2026-05-15',
    status: 'open',
    estimatedValue: 18500000,
    highestBid: 17200000,
    totalBids: 8,
    description: 'Mechanical, Electrical, and Plumbing systems for Grade-A commercial office building. HVAC, fire safety, and BMS included.',
    attachments: [
      { name: 'MEP Drawings.pdf', size: '15.3 MB' },
      { name: 'Equipment List.xlsx', size: '1.2 MB' },
    ],
    category: 'Services',
  },
];
